version: '3.8'

services:  
  db:
    container_name: pearchace-db
    image: postgres:16   
    environment:      
      POSTGRES_DB: pearchdb      
      POSTGRES_USER: pearchuser      
      POSTGRES_PASSWORD: PearchTest@123    
    volumes:      
      - postgres_data:/var/lib/postgresql/data    
    ports:      
      - "5432:5432"  
  
  web:    
    container_name: pearchace-web
    build: .   
    command: gunicorn --bind 0.0.0.0:8000 shopify_django_app.wsgi:application    
    volumes:      
      - .:/app    
    ports:      
      - "8000:8000"  
    depends_on:      
      - db
    networks:
      - pearch_network  

  nginx:
    container_name: pearchace-nginx
    image: nginx:latest
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt 
    depends_on:
      - web
    networks:
      - pearch_network

volumes:  
  postgres_data:

networks:
  pearch_network:
    driver: bridge